In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
col_1=np.array([10,20,30,40,50,60,70,80,90])
col_2=np.array([15,25,35,45,55,65,75,85,95])

In [3]:
out=[]
for i in range(len(col_1)):
    out.append(col_1[i]+col_2[i])
out_col=np.array(out)
out_col

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [4]:
out_col=np.array([col_1[i]+col_1[i] for i in range(len(col_1))])

In [5]:
out_col

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [6]:
col_1=col_1.reshape(len(col_1),1)
col_2=col_2.reshape(len(col_2),1)
out_col=out_col.reshape(len(out_col),1)

In [7]:
data=np.hstack((col_1,col_2,out_col))

In [8]:
## Feature and target Data
def feature_transform(n_steps,data):
    x=[]
    y=[]
    for i in range(n_steps,len(data)+1):
        x.append(data[i-n_steps,i:-1])
        y.append(data[i-1,-1])
    return np.array(x),np.array(y)

In [9]:
n_steps=3
x,y=feature_transform(n_steps,data)

In [10]:
x,y

(array([], shape=(7, 0), dtype=int32),
 array([ 60,  80, 100, 120, 140, 160, 180]))

array([], shape=(7, 0), dtype=int32)

In [11]:
from keras.models import Sequential
from keras.layers import Dense,LSTM
model=Sequential()
model.add(LSTM(50,activation="relu",input_shape=(n_steps,x.shape[2])))
model.add(Dense(1))
model.compile(loss="mean_squared_error",optimizer="adam")

IndexError: tuple index out of range

In [ ]:
history=model.fit(x,y,epochs=100)

In [ ]:
xtest=np.array([[80,85],[90,95],[100,105]])
xtest=xtest.reshape(1,n_steps,2)
ypred=model.predict(xtest)
ypred