# Welcome to Numpy tutorial

In [2]:
import numpy as np

In [3]:
myarr=np.array([3,6,32,7],np.int8)

In [5]:
myarr[0]

3

In [6]:
myarr.shape

(4,)

In [7]:
myarr.dtype

dtype('int8')

In [3]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.dtype

dtype('int32')

In [6]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

In [8]:
np.array({34,23})

array({34, 23}, dtype=object)

In [10]:
zeros=np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(1,5,12)

In [15]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [16]:
  np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261434e-306, 7.56599807e-307, 7.56599807e-307],
       [8.90104239e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.60217812e-306, 1.37961370e-306,
        8.01091099e-307, 8.90104239e-307, 1.11260144e-306],
       [1.02360256e-306, 8.34451504e-308, 1.33508761e-307,
        1.33511562e-306, 8.90103560e-307, 1.42410974e-306]])

In [17]:
emp_like=np.empty_like(lspace)

In [18]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [19]:
ide=np.identity(45)

In [20]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
ide.shape

(45, 45)

In [22]:
arr=np.arange(99)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr=arr.reshape(3,33)

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr=arr.ravel()

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape

(99,)

In [30]:
# Axis 0 for row and Axis 1 for columns

In [31]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [33]:
ar=np.array(x)

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [40]:
ar.ndim

2

In [41]:
ar.size

9

In [42]:
ar.nbytes

36

In [43]:
one=np.array([1,3,4,634,2])

In [44]:
one.argmax()     #its gives the index value where max number is stored

3

In [45]:
one.argmin()

0

In [46]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.argmin()

8

In [49]:
ar.argmax()

6

In [50]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [51]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [53]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [55]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)