In [1]:
import numpy as np

In [2]:
# data matrix for PCA
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
# Mean of Each Column
M=np.mean(data.T,axis=1)
M

array([3., 4.])

In [4]:
# Subtract Mean From Data
scale_data=data-M
scale_data

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [5]:
# Covariance matrix on scaled Data
v=np.cov(scale_data.T)
v

array([[4., 4.],
       [4., 4.]])

In [6]:
# Eigen value and Eigen Vector
values,vectors=np.linalg.eig(v)

In [7]:
# eigen values which is explained variance of component
values

array([8., 0.])

In [9]:
# Eigen Vectors which are principle Component
vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [11]:
# project the data/ Transfer the data
p=vectors.T.dot(scale_data.T)

In [12]:
p.T

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [13]:
from sklearn.decomposition import PCA

In [14]:
pca=PCA()
pca.fit(data)

PCA()

In [15]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [19]:
pca.explained_variance_

array([8., 0.])

In [22]:
p=pca.transform(data)
p

array([[-2.82842712e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00,  2.22044605e-16]])