In [1]:
# Mean absolute error= summ (y-ypred)/N

# Mean error Sequence = summ(y-ypred)^2/N

## Regularazation

### Ridge regression
### optimization
###       |
###       |
### minimize loss function
### y-ypred 1+ab    ---a for alfa b for beta

In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [33]:
df=pd.read_csv("C:\\Users\\Krishna\\Desktop\\dataset\\housing.csv")
df

RM  LSTAT  PTRATIO    MEDV
0    6.575   4.98     15.3  504000
1    6.421   9.14     17.8  453600
2    7.185   4.03     17.8  728700
3    6.998   2.94     18.7  701400
4    7.147   5.33     18.7  760200
..     ...    ...      ...     ...
484  6.593   9.67     21.0  470400
485  6.120   9.08     21.0  432600
486  6.976   5.64     21.0  501900
487  6.794   6.48     21.0  462000
488  6.030   7.88     21.0  249900

[489 rows x 4 columns]

In [37]:
x=df[["RM","LSTAT","PTRATIO"]]
y=df["MEDV"]

In [39]:
model=LinearRegression()
model.fit(x,y)
model.score(x,y)

0.7176275212982738

In [80]:
ypred=model.predict(x)
pd.DataFrame({"Actual":y,"Predicted":ypred})

Actual      Predicted
0    504000  632371.739762
1    453600  525177.148313
2    728700  646753.118080
3    701400  624848.295870
4    760200  611816.592536
..      ...            ...
484  470400  471941.448492
485  432600  437397.202628
486  501900  548818.775678
487  462000  523950.456779
488  249900  442625.539836

[489 rows x 2 columns]

#### using this concept Overfit

In [84]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=10)
ridge_model.fit(x,y)
ridge_model.score(x,y)

0.7172506647287367

In [85]:
ridge_model.coef_

array([ 80229.90274493, -11187.58081659, -19581.37130375])

In [86]:
ridge_model.coef_

array([ 80229.90274493, -11187.58081659, -19581.37130375])

In [87]:
ypred=ridge_model.predict(x)
pd.DataFrame({"Actual":y,"Predicted":ypred})

Actual      Predicted
0    504000  633230.595777
1    453600  525381.426297
2    728700  643845.609967
3    701400  623413.847071
4    760200  608629.784428
..      ...            ...
484  470400  470591.163565
485  432600  439243.092248
486  501900  546405.167007
487  462000  522405.756821
488  249900  445447.497981

[489 rows x 2 columns]

In [100]:
from sklearn.linear_model import Lasso
lasso_model=Lasso(alpha=10)
lasso_model.fit(x,y)
lasso_model.score(x,y)

0.7176275096507371

In [99]:
lasso_model.coef_

array([ 86531.23453251, -10851.19509228, -19490.78215712])

In [98]:
ypred=lasso_model.predict(x)
pd.DataFrame({"Actual":y,"Predicted":ypred})

Actual      Predicted
0    504000  632370.832609
1    453600  525177.095514
2    728700  646736.565618
3    701400  624841.323470
4    760200  611800.121145
..      ...            ...
484  470400  471938.831552
485  432600  437411.762723
486  501900  548810.610600
487  462000  523946.922037
488  249900  442645.385725

[489 rows x 2 columns]

In [89]:
from sklearn.preprocessing import PolynomialFeatures
poly_trans=PolynomialFeatures(degree=4)
x_poly=poly_trans.fit_transform(x)

In [90]:
x_poly

array([[1.00000000e+00, 6.57500000e+00, 4.98000000e+00, ...,
        5.80552564e+03, 1.78362535e+04, 5.47981281e+04],
       [1.00000000e+00, 6.42100000e+00, 9.14000000e+00, ...,
        2.64686869e+04, 5.15473333e+04, 1.00387586e+05],
       [1.00000000e+00, 7.18500000e+00, 4.03000000e+00, ...,
        5.14576676e+03, 2.27282006e+04, 1.00387586e+05],
       ...,
       [1.00000000e+00, 6.97600000e+00, 5.64000000e+00, ...,
        1.40280336e+04, 5.22320400e+04, 1.94481000e+05],
       [1.00000000e+00, 6.79400000e+00, 6.48000000e+00, ...,
        1.85177664e+04, 6.00112800e+04, 1.94481000e+05],
       [1.00000000e+00, 6.03000000e+00, 7.88000000e+00, ...,
        2.73836304e+04, 7.29766800e+04, 1.94481000e+05]])

In [91]:
poly_model=LinearRegression()
poly_model.fit(x_poly,y)

LinearRegression()

In [92]:
poly_model.score(x_poly,y)

0.8612239920129288

In [93]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=0.3)
ridge_model.fit(x_poly,y)
ridge_model.score(x_poly,y)

0.8536149242660724

In [94]:
ridge_model.coef_

array([ 0.00000000e+00,  3.30026901e+03, -2.92141328e+04, -9.73247614e+03,
        1.14080057e+04, -5.55023158e+04, -1.68789254e+04, -2.31728941e+04,
        7.67439709e+04, -4.97862287e+03,  2.34601454e+04, -7.92111776e+03,
       -8.80964039e+03,  3.45937671e+03,  3.20618420e+03,  3.52923494e+03,
        1.25013215e+02,  8.73028020e+02, -5.49602840e+03,  4.60696086e+02,
       -1.11177527e+03,  1.54450520e+03, -1.11892245e+03, -1.31764616e+01,
       -1.07309917e+03,  1.08437858e+03, -3.08385395e+01, -7.05434589e+01,
        3.36236682e+02, -3.91215273e+02, -1.22457625e+00,  9.23770305e+00,
       -2.60391718e+01,  7.57074027e+01,  2.10374761e+01])

In [101]:
from sklearn.linear_model import ElasticNet
ENet_model=ElasticNet(alpha=0.1,11_ratio=0.5)
ENet_model.fit(x,y)
ENet_model.score(x,y)

SyntaxError: invalid decimal literal (<ipython-input-101-fee741062858>, line 2)